# -*- coding: utf-8 -*-
"""
Continuum source: builds States from the tables written by the continuum scripts
(Continuum_Mechanics_Solution/Scripts/), one entry per alloy in ALLOYS.

The scripts are NOT imported (importing runs the whole solution and rewrites the CSVs);
their tables and parameters are read as they are. Line numbers (Lxxx) refer to the
nucleation script of each alloy.

Row i of a table is one point of the continuum loop, r = req - i·dreq.
In `tablefull` (Al3Cu5Nb01Fe) the extra row with non-integer i (38.5) is the interpolated
experimental point (L1029-L1036).
"""
from pathlib import Path

import numpy as np
import pandas as pd

from ..quantity import Quantity
from ..state import State
from ..surface import gurtin_murdoch_legacy

ROOT = Path(__file__).resolve().parents[2]
SCRIPTS_DIR = ROOT / "Continuum_Mechanics_Solution" / "Scripts"
TABLEFULL = SCRIPTS_DIR / "tablefull_paper_B_MRS_2026.csv"

# Values used by the continuum script (copied, not chosen here)
# Nucleation_model_FCC_A1_new_paper_B_MRS_Meeting_2026_dev_full_GLH_AlCuNbFe_signal_beta_2nd_Sim_2026_paper.py
CONTINUUM_PARAMS = dict(
    TL=936.58,          # L218  liquidus [K]
    DeltaH=335300.0,    # L219  [J/kg]
    rhos=2737.04,       # L221  [kg/m3]
    sigma_0=1.3761,     # L224  surface stress σ0 [N/m]
    gamma_0=0.296,      # L226  γ0 [J/m2]
    mu0=1.6,            # L227  surface Lamé μ0 [N/m]
    lambda0=-5.0,       # L228  surface Lamé λ0 [N/m]
    mu=2.594e10,        # L230  bulk μ [Pa]
    lambda_=5.034e10,   # L231  bulk λ [Pa]
    req=6.3e-6,         # L750  r0 [m]
    ad=0.25e-9,         # L235  jump distance λ [m]
)


# Nucleation_model_FCC_A1_new_paper_2024_dev_full_GLH_AlSiMgFe_signal_beta_2nd_Sim_Luane.py
PARAMS_AL08SI06MG02FE = dict(
    TL=925.32,          # L190
    DeltaH=335300.0,    # L191
    rhos=2555.72,       # L193
    sigma_0=1.09,       # L196
    gamma_0=0.183,      # L198
    mu0=1.6,            # L199
    lambda0=-5.0,       # L200
    mu=2.594e10,        # L202
    lambda_=5.034e10,   # L203
    req=6.3e-6,         # L685
    ad=0.25e-9,         # L207
)

# `tabela_paper.csv` header names 10 columns but each row has 11 (GT_het is not in the header,
# L762 vs L875); the names below follow the row format of L875.
TABELA_COLUMNS = ["i", "dTdr", "DT", "r_hom_2nd", "r_het_2nd", "theta_2nd", "sigma",
                  "surface_stress", "gam_hom", "GT_het", "GT_het_2nd"]

ALLOYS = {
    "Al3Cu5Nb01Fe": dict(table=TABLEFULL, kind="tablefull", params=CONTINUUM_PARAMS,
                         grad_T_exp=3294.0, experiment="Mendes et al. (2023)"),
    "Al08Si06Mg02Fe": dict(table=ROOT / "data" / "continuum" / "Al08Si06Mg02Fe" / "tabela_paper.csv",
                           kind="tabela", params=PARAMS_AL08SI06MG02FE,
                           grad_T_exp=7902.38, experiment="Marques et al. (2025)"),
}


def delta_Sv_constant(p=CONTINUUM_PARAMS):
    """L222: ΔS_V = -ΔH·ρ_s/T_L  [J m^-3 K^-1]."""
    return -p["DeltaH"] * p["rhos"] / p["TL"]


def dself_legacy(T, Tm):
    """`Dself` (L585): Al liquid self-diffusion [m2/s]."""
    DTm, p, q = 7.44e-9, 0.10, -0.11
    return DTm * (T / Tm) ** 1.5 / ((1 + p - p * T / Tm) * (1 - q + q * T / Tm) ** (2 / 3))


def read_tablefull(path=TABLEFULL):
    t = pd.read_csv(path, sep=";", skipinitialspace=True)
    t.columns = [c.strip() for c in t.columns]
    return t


def read_tabela(path):
    """`tabela_paper.csv` (row format of L875); generated by scripts/run_continuum.py."""
    if not Path(path).exists():
        raise FileNotFoundError(f"{path} missing: run `python scripts/run_continuum.py`")
    return pd.read_csv(path, sep=";", skiprows=1, header=None, names=TABELA_COLUMNS)


class ContinuumSource:
    """
    dSv_mode   - "closure":    ΔS_V = -ΔH·ρ_s/T_L (L222) with ∂ΔS_V/∂r from the closure (L902)
                               -3(ΔS_VΔT + ∂γ/∂r)/(2rΔT) - (ΔS_V/ΔT)·∂ΔT/∂r,
                               which makes -3b/(2a) = r for a homogeneous nucleus
                 "integrated": ΔS_V(r) = column DSv_hom (L937, the value used for GB)
                 "constant":   ΔS_V = -ΔH·ρ_s/T_L, ∂ΔS_V/∂r = 0
    theta_mode - "table": θ(r) = column theta_2nd;  "homogeneous": θ = π
    df_mode    - passed to State ("chain" or "continuum_legacy")

    ΔT(r), θ(r) (and ΔS_V(r) when integrated) are cubic splines over the loop rows
    (radius = r_hom_2nd); γ(r) is the Gurtin–Murdoch expression of the script.
    """

    def __init__(self, path=None, params=None, dSv_mode="closure", df_mode="chain",
                 theta_mode="table", alloy="Al3Cu5Nb01Fe"):
        cfg = ALLOYS[alloy]
        self.alloy = alloy
        self.grad_T_exp = cfg["grad_T_exp"]
        path = cfg["table"] if path is None else path
        params = cfg["params"] if params is None else params
        if dSv_mode not in ("closure", "integrated", "constant"):
            raise ValueError("dSv_mode must be 'closure', 'integrated' or 'constant'")
        if theta_mode not in ("table", "homogeneous"):
            raise ValueError("theta_mode must be 'table' or 'homogeneous'")
        self.params = dict(params)
        table = read_tablefull(path) if cfg["kind"] == "tablefull" else read_tabela(path)
        if dSv_mode == "integrated" and "DSv_hom" not in table:
            raise ValueError(f"{alloy}: the table has no DSv_hom column (dSv_mode='integrated')")
        is_loop = np.isclose(table["i"], np.round(table["i"]))
        self.table = table[is_loop].reset_index(drop=True)
        self.experimental = table[~is_loop].reset_index(drop=True)
        self.dSv_mode = dSv_mode
        self.theta_mode = theta_mode
        self.df_mode = df_mode

        t, p = self.table, self.params
        r = t["r_hom_2nd"].to_numpy()
        self.DT = Quantity.tabulated(r, t["DT"], "DT")
        if theta_mode == "table":
            self.theta = Quantity.tabulated(r, t["theta_2nd"], "theta_2nd")
        else:
            self.theta = Quantity.constant(np.pi, "theta_hom")
        self.gamma = gurtin_murdoch_legacy(p["gamma_0"], p["req"], p["sigma_0"],
                                           p["lambda_"], p["mu"], p["lambda0"], p["mu0"])
        DSv0 = delta_Sv_constant(p)
        self.DSv0 = DSv0
        if dSv_mode == "integrated":
            self.DSv = Quantity.tabulated(r, t["DSv_hom"], "DSv_hom")
        elif dSv_mode == "constant":
            self.DSv = Quantity.constant(DSv0, "DSv_const")
        else:
            DT, gam = self.DT, self.gamma

            def closure(x):
                return (-3.0 * (DSv0 * DT(x) + gam.d(x)) / (2.0 * x * DT(x))
                        - DSv0 / DT(x) * DT.d(x))

            self.DSv = Quantity(lambda x: np.full_like(np.asarray(x, dtype=float), DSv0),
                                closure, "DSv_closure")

    @property
    def rows(self):
        return self.table["i"].astype(int).tolist()

    def row(self, i):
        return self.table[self.table["i"] == i].iloc[0]

    def state(self, i, df_mode=None):
        r = float(self.row(i)["r_hom_2nd"])
        return State(self.DSv, self.DT, self.gamma, self.theta, r_eval=r,
                     T_m=self.params["TL"], df_mode=df_mode or self.df_mode,
                     label=f"continuum i={i}")

    def radius_at_gradient(self, grad_T):
        """r for a given ∇T [K/m]: linear interpolation of the dTdr column, as in L1036."""
        t = self.table
        g, r = t["dTdr"].to_numpy(), t["r_hom_2nd"].to_numpy()
        if not (g.min() <= grad_T <= g.max()):
            raise ValueError(f"grad_T={grad_T} outside the continuum range [{g.min()}, {g.max()}]")
        order = np.argsort(g)
        return float(np.interp(grad_T, g[order], r[order]))

    def state_at_gradient(self, grad_T, df_mode=None):
        """State selected by the thermal gradient (the variable that displaces the equilibrium)."""
        return State(self.DSv, self.DT, self.gamma, self.theta,
                     r_eval=self.radius_at_gradient(grad_T), T_m=self.params["TL"],
                     df_mode=df_mode or self.df_mode, label=f"continuum gradT={grad_T}")

    def reference_state(self):
        """The continuum normalises the rate by row i=1 (L918, L928)."""
        return self.state(1)
